module.exports = {
  scrapeUSportsStandings: require('./usports'),
  scrapeUSportsWStandings: require('./usportsW'),
  scrapeCPLStandings: require('./cpl'),
  scrapeL1OPremierStandings: require('./l1oPremier'),
  scrapeL1OChampionshipStandings: require('./l1oChampionship'),
  scrapeL2OSouthwestStandings: require('./l2oSouthwest'),
  scrapeL2ONortheastStandings: require('./l2oNortheast'),
  scrapeL2OCentralStandings: require('./l2oCentral'),
  scrapeL1AlbertaStandings: require('./l1Alberta'),
  scrapeL1BCStandings: require('./l1BC'),
  scrapeL1QuebecStandings: require('./l1Quebec'),
  scrapeL2QuebecStandings: require('./l2Quebec'),
  scrapeL3QuebecStandings: require('./l3Quebec'),
  scrapeL1AlbertaWStandings: require('./l1AlbertaW'),
  scrapeL1BCWStandings: require('./l1BCW'),
  scrapeL1OChampionshipWStandings: require('./l1oChampionshipW'),
  scrapeL1OPremierWStandings: require('./l1oPremierW'),
  scrapeL2OSouthwestWStandings: require('./l2oSouthwestW'),
  scrapeL2ONortheastWStandings: require('./l2oNortheastW'),
  scrapeL1QuebecWStandings: require('./l1QuebecW'),
  scrapeL2QuebecWStandings: require('./l2QuebecW'),
  scrapeNCAAMensStandings: require('./ncaa'),
  scrapeNCAAWomensStandings: require('./ncaaw'),
  scrapeMLSstandings: require('./mls'),
  scrapeMLSNPstandings: require('./mlsnp'),
  scrapeNSLStandings: require('./nsl'),
  scrapeUSLChampionshipStandings: require('./uslc'),
  scrapeUSL1Standings: require('./usl1'),
  scrapeOPDLU17Boys: require('./opdlb'),
  scrapeOPDLU17Girls: require('./opdlw'),
  scrapeOCAAMensStandings: require('./ocaa'),
  scrapeOCAAWStandings: require('./ocaaw'),

};
